### PR TITLE
ING-667: Added support for query durability_level.

### PR DESCRIPTION
**Pull request by brett19**

### CODE REVIEW

**Review by chvck — APPROVED** [review]
This looks good to me, but given it's a query specific durability level more opinions would be good.

**Review by Westwooo — APPROVED** [review]

**Comment by brett19** [comment]
@programmatix Would you be able to take a look at this before we merge?  One thing I'm not sure about is whether we should distinguish "NO_DURABILITY" as an explicitly specifiable enumeration, in case the default in the server changes?

**Comment by programmatix** [comment]
Sorry, I didn't see this before.  IMO being able to specify no durability is a good idea in case there are situations now or in future involving things like overriding bucket-level durability levels.

**Comment by brett19** [comment]
I've added an explicit 'NONE' option for durability here.

**Review by dnault — APPROVED** [review]

**Pull request merged**
