### PR TITLE
Add C# Namespaces to avoid conflicts in SDK

### PR DESCRIPTION
**Pull request by SecureCake**

### CODE REVIEW

**Review by programmatix — APPROVED** [review]

**Comment by chvck** [comment]
Would  it make sense for this change to be applied to every proto file rather than just a selection?

**Comment by SecureCake** [comment]
Some could get away without, but for consistency I think it's better if we prefix all with "Couchbase.Protostellar". The SDK already has Couchbase.Kv, Couchbase.View, Couchbase.Analytics etc...

**Comment by SecureCake** [comment]
Thanks both! Could one of you with write access help me merge it?

**Comment by chvck** [comment]
> Some could get away without, but for consistency I think it's better if we prefix all with "Couchbase.Protostellar". The SDK already has Couchbase.Kv, Couchbase.View, Couchbase.Analytics etc...

I think we should probably apply to all files for consitency first.

**Pull request merged**
